//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommercesite.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/balancecheck", ReplyAction="http://tempuri.org/IService/balancecheckResponse")]
        string balancecheck(string accno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/balancecheck", ReplyAction="http://tempuri.org/IService/balancecheckResponse")]
        System.Threading.Tasks.Task<string> balancecheckAsync(string accno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/amountreduction", ReplyAction="http://tempuri.org/IService/amountreductionResponse")]
        int amountreduction(string accno, int id, int amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/amountreduction", ReplyAction="http://tempuri.org/IService/amountreductionResponse")]
        System.Threading.Tasks.Task<int> amountreductionAsync(string accno, int id, int amount);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : Ecommercesite.ServiceReference2.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<Ecommercesite.ServiceReference2.IService>, Ecommercesite.ServiceReference2.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string balancecheck(string accno) {
            return base.Channel.balancecheck(accno);
        }
        
        public System.Threading.Tasks.Task<string> balancecheckAsync(string accno) {
            return base.Channel.balancecheckAsync(accno);
        }
        
        public int amountreduction(string accno, int id, int amount) {
            return base.Channel.amountreduction(accno, id, amount);
        }
        
        public System.Threading.Tasks.Task<int> amountreductionAsync(string accno, int id, int amount) {
            return base.Channel.amountreductionAsync(accno, id, amount);
        }
    }
}
